//
//  DisplayDataModels.swift
//  Agri10x
//
//  Created by Akash Kumar on 06/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DisplayData
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
struct UserDetails: Codable {
    var id: Int?
    var title:String?
    var price:Double?
    var description:String?
    var category:String?
    var image:String?
    var rating:Ratings?
    
    init( id:Int,title:String,price: Double, description:String, category:String, image:String, rating:Ratings ) {
        self.id = id
        self.title = title
        self.price = price
        self.description = description
        self.category = category
        self.image = image
        self.rating = rating
    }
}

struct Ratings: Codable {
    var rate: Double?
    var count: Int?
    
    init(rate:Double, count:Int) {
        self.rate = rate
        self.count = count
    }
}

struct DataDetails : Equatable {
    var id: Int?
    var title:String?
    var price:Double?
    var description:String?
    var category:String?
    var image:String?
    var rate: Double?
    var count: Int?
    
    init(data:UserDetails) {
        self.id = data.id
        self.title = data.title
        self.price = data.price
        self.description = data.description
        self.category = data.category
        self.image = data.image
        self.rate = data.rating?.rate
        self.count = data.rating?.count
    }
}
