//
//  FavouriteViewController.swift
//  Agri10x
//
//  Created by Akash Kumar on 06/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouriteDisplayLogic: class
{
  func displaySomething(viewModel: Favourite.Something.ViewModel)
}

class FavouriteViewController: UIViewController, FavouriteDisplayLogic
{
    @IBOutlet weak var tableView: UITableView!
    var userData:[Details] = []
    var userDeletedData:[Details] = [] {
        didSet {
            DispatchQueue.main.async {
                self.tableView.reloadData()
            }
        }
    }
  var interactor: FavouriteBusinessLogic?
  var router: (NSObjectProtocol & FavouriteRoutingLogic & FavouriteDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FavouriteInteractor()
    let presenter = FavouritePresenter()
    let router = FavouriteRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
    tableView.separatorStyle = .none
    tableView.rowHeight = UITableView.automaticDimension
    tableView.estimatedRowHeight = 100
    let bundle = Bundle(for: type(of: self))
    self.tableView.register(UINib(nibName: "DisplayDataTableViewCell", bundle: bundle),
                            forCellReuseIdentifier: "DisplayDataTableViewCell")
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Favourite.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Favourite.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    class func instance() -> FavouriteViewController? {
        return StoryBoard.Favourite.board.instantiateViewController(withIdentifier: AppClass.FavouriteVC.rawValue) as? FavouriteViewController
    }
}
