//
//  FavouritePresenter.swift
//  Agri10x
//
//  Created by Akash Kumar on 06/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouritePresentationLogic
{
  func presentSomething(response: Favourite.Something.Response)
}

class FavouritePresenter: FavouritePresentationLogic
{
  weak var viewController: FavouriteDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Favourite.Something.Response)
  {
    let viewModel = Favourite.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
